### ISSUE TITLE
Can you add a "back to top" button at the bottom of the post?

### ISSUE THREAD

**Issue by bnulhf** [the-open-agent/openagent#109]
Can you add a "back to top" button at the bottom of a post's reply, so that you can click back to the top after browsing all the replies.
As shown in the figure:
![image](https://user-images.githubusercontent.com/57997507/103652008-681b2000-4f9d-11eb-83e1-c6ab9ffb1174.png)

**Comment by hsluoyz** [comment]
@bnulhf fixed in: https://github.com/casbin/casbin-forum/commit/00cabc27df80a68e8865ed55a0e03551a3ee0520

![image](https://user-images.githubusercontent.com/3787410/103914376-b159a400-5144-11eb-9755-ca3deb346509.png)
