### ISSUE TITLE
Integrate open-source mailing list functionality to our forum

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#112]
An open-source community (including Casbin) usually uses a mailing list for community connections like questions, issues, annoucements, etc.

The mailing list is usually done by a self-maintained mailing list software like Mailman used by Nmap: https://nmap.org/mailman/listinfo (see more at: https://en.wikipedia.org/wiki/List_of_mailing_list_software) or an online service/provider like Google Groups used by Casbin: https://groups.google.com/g/casbin

A mailing list allows:

1. All the people that subscribed the mailing list will receive Email notification whenever a person posts a new topic/thread or reply to an existing topic/thread/post.
2. If a person replies to the Email he/she received, the reply will be collected by the mailing list for a central storage and also sent to all subscribers via Email.

This is similar to what a forum (like Casbin-Forum) does. Actually there are some work about forum & mailing list integration:

- https://www.freelists.org/
- https://www.freelock.com/blog/john-locke/2010-03/mailing-list-or-forum-theory
- http://doc.tiki.org/Forum-and-Mailing-List-Synchronization
- https://elixirforum.com/t/how-to-use-this-forum-as-a-mailing-list/90
- https://wordpress.org/support/topic/forum-mailing-list-integration/

We also want to do it:

1. A Casbin-Forum node can bind to a mailing list Email like: `dev@casbin.org`.
2. A forum user can click a button to subscribe the node (aka the mailing list).
3. All the posts and replies of that node will be bidirectionally synced with the mailing list.

Hope somebody can work on it.

**Comment by oceanlvr** [comment]
I would like to work on this issue. And I need more time to figure out how to configure `mailman3` and it's API.

ref: [docker-mailman#configuration](https://github.com/maxking/docker-mailman#configuration)

**Comment by hsluoyz** [comment]
@oceanlvr we don't need to directly use the mailman code. Just follow its behavior. For example, GitHub is actually like this:

1. If you reply to the Email sent by GitHub Notification, the reply will also show in GitHub.
2. Vice versa.

**Comment by hsluoyz** [comment]
@Kininaru

**Comment by hsluoyz** [comment]
@Kininaru next step we can do this.

**Comment by keainye** [comment]
@hsluoyz Got that, I'll work on this.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casnode/pull/224
