### ISSUE TITLE
3rd-party login panel has style issues

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#114]
See: https://forum.casbin.com/signin

![image](https://user-images.githubusercontent.com/3787410/104795302-0d2cc880-57e8-11eb-99b3-e33156c1b1ea.png)

**Comment by pranav1698** [comment]
@hsluoyz I would like to work on this

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin-forum/pull/117
