### ISSUE TITLE
Make it SEO friendly via SSR

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#122]
Refer to: https://forum.casbin.com/t/75

As we know, SPA is not friendly for SEO like Googlebot. We need to add SSR (Server-Side Rendering) to this React app, like using Next.js: https://nextjs.org/

**Comment by hsluoyz** [comment]
@oceanlvr can you take this task?

**Comment by oceanlvr** [comment]
@hsluoyz I'll do this. This is a long time of work.

**Comment by specter25** [comment]
@hsluoyz can I take it up ?

**Comment by hsluoyz** [comment]
@specter25 sure.

**Comment by maansiii** [comment]
We can use cloud platform like vercel for deploying, for installation type `yarn global add vercel` on cmd and inside your project
type `vercel` on cmd so the project will be deployed using SSL certificate.
If that helps^

**Comment by Hanaffi** [comment]
@hsluoyz  Can we use React Helmet?

**Comment by hsluoyz** [comment]
> @hsluoyz Can we use React Helmet?

@Hanaffi we use Go backend

**Comment by hsluoyz** [comment]
@Kininaru

**Comment by hsluoyz** [comment]
@Kininaru I think we can use this one: https://github.com/rendora/rendora

**Comment by keainye** [comment]
@hsluoyz Working on this.
