### ISSUE TITLE
What knowledge is needed to fully understand  the front-end code of this forum?

### ISSUE THREAD

**Issue by yanshenxian** [the-open-agent/openagent#128]
In other words, can you recommend a learning roadmap of **React** for this project? Thanks~

**Comment by hsluoyz** [comment]
Hi @yanshenxian , can you modify your question into English to let developers all over the world be able to read it? Thanks.

**Comment by hsluoyz** [comment]
@yanshenxian It's a normal React project, so you will need:

1. Basic knowledge of HTML, JS, CSS..
2. Knowledge of React.

So may I know that whether you are a user of casbin-forum or want to contribute to it (for interest or gsoc)?

**Comment by yanshenxian** [comment]
@hsluoyz HH. I'm a mere beginner with React. And I wonder more detail about React like the components used.Then maybe it's convenient to learn the project.Finally instead of write a forum product, I want to write something else inspired by casbin-forum project just for interest.

**Comment by hsluoyz** [comment]
@yanshenxian good to hear!
