### ISSUE TITLE
The text area is at risk of XSS injection

### ISSUE THREAD

**Issue by oceanlvr** [the-open-agent/openagent#131]
ref: [https://forum.casbin.com/t/82](https://forum.casbin.com/t/82)

When I review the old version code. I think the `<textarea>`  is at risk of XSS injection. because it's doesn't deal with the text data encode and decode, here is source code:

https://github.com/casbin/casbin-forum/blob/9f21cfaa6c7d9518dcc87eb7cb34f3896549cf23/web/src/main/NewNodeTopicBox.js#L300

![xss](https://user-images.githubusercontent.com/36698124/107190011-34606980-6a25-11eb-856d-a5873cd96e44.gif)

**Comment by hsluoyz** [comment]
@oceanlvr great found! Let's fix it!

**Comment by ChelesteWang** [comment]
I think we should restrict the rich text area, or try to mount it with other editors，If you still use markdown syntax, you can limit the script and iframe tags, and use the loader for secondary processing of the video
