### ISSUE TITLE
The ranking pages do not display correctly

### ISSUE THREAD

**Issue by mit1987** [the-open-agent/openagent#132]
On the main  page, the ranking pages, for example ranking of wealth, are not operating. After clicking, the page show nothing.
Please fix this bug.
And in the posts, if you upload a video links, you cannot size up the video in PC. But it can be done in mobile phones.

**Comment by oceanlvr** [comment]
@mit1987 thx for your support.
Could you plz give us more detail?  better screenshot.
thank you！
