### ISSUE TITLE
Try to use docker to simplify the deployment process of casbin-forum

### ISSUE THREAD

**Issue by ChelesteWang** [the-open-agent/openagent#133]
I want to try to use docker to simplify the deployment process of casbin-forum , This will make it easier for more users and developers to try the forum

**Comment by oceanlvr** [comment]
This is a very good idea, I think `casbin-forum` currently just a simple SPA application with just `node` and `go` environment dependence.
I'll consider put `casbin-forum` to the docker container.

**Comment by ChelesteWang** [comment]
I have tried to use docker package for the current version，I think that It is not a good idea for beginners ，Using docker is not friendly for configuration modification ，It is recommended that developers and users try to modify the configuration and use dockerfile to build themselves

**Comment by oceanlvr** [comment]
Maybe you can put your completed code as a new PR, I want to see if it fits(if it's not too much trouble)
:)

**Comment by oranges-eating** [comment]
I will work for it

**Comment by t3link** [comment]
Installation document in README.md is outdated.
1. without any explanation about [casdoor](https://github.com/casbin/casdoor)  requirement
2. `web/src/main/custom/` in custom setting no longer exist

**Comment by oranges-eating** [comment]
> README.md 中的安装文档已过时。
> 
> 1. 没有关于[casdoor](https://github.com/casbin/casdoor)  要求的任何解释
> 2. `web/src/main/custom/` 在自定义设置中不再存在

Yes, I have added docker installation documentation for it now. I will update the readme after merging the PR.

**Comment by hsluoyz** [comment]
@oranges-eating plz update README.
