### ISSUE TITLE
Remove jquery dependency

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#139]
I don't know why we introduced jquery at the first time, but given that jquery is deprecated, I think we should remove it: https://github.com/casbin/casbin-forum/search?q=jquery

**Comment by Pustur** [comment]
Select2 depends on jQuery so you would have to replace it as well.

**Comment by hsluoyz** [comment]
@Pustur this commit: https://github.com/casbin/casbin-forum/commit/0705ba2d481ba93022de05869de4a111d450ba19 introduced Select2 and jquery. But the only code that used jquery is this:

L139:

```js
              onSelect={event => {
                const s = $(event.target).val();
                if (s === null) {
                  return;
                }
```

I think it can be easily replaced by DOM API?

**Comment by Pustur** [comment]
You can easily remove jQuery from your code (I see it's always used to get the element's value, like you mentioned above) but as long as you are using Select2, jQuery will still be needed for Select2's internal code.

BTW if you just want to remove the instances where you use jQuery in your own code, I can make a PR for that if you're interested.

**Comment by hsluoyz** [comment]
@Pustur sure!

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin-forum/commit/e250813b1246e5ec00e93431785970a436df5bd0
