### ISSUE TITLE
CSS style error for link page

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#143]
See: https://forum.casbin.com/go/node-casbin/links

![image](https://user-images.githubusercontent.com/3787410/107866321-6c92fc80-6eaa-11eb-94f9-bbe96198c66a.png)

**Comment by hsluoyz** [comment]
@oceanlvr I don't think this issue got fixed, see: https://forum.casbin.com/go/casbin/links

![image](https://user-images.githubusercontent.com/3787410/109173534-e7b7b500-77be-11eb-9377-38fdb9aff271.png)

**Comment by oceanlvr** [comment]
@hsluoyz Sorry, it was my mistake that caused not all file to be submitted completely, I do some change in `app.js` but not commit.

I fix this style error now.
