### ISSUE TITLE
Use Casdoor as the authentication system

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#145]
We have developed the Casdoor: https://github.com/casbin/casdoor , which is also officially hosted at: https://door.casbin.com/ It is already successfully deployed to: https://oa.casbin.com/

We will move the authentication (user table, password login, Email, SMS, OAuth providers like GitHub, Google, etc.) of this forum to Casdoor finally.

**Comment by hsluoyz** [comment]
@oceanlvr

**Comment by oceanlvr** [comment]
@hsluoyz I will replace the existing user authentication with casdoor

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casnode/commit/9f260a7a014a31b82478ab0d308612a130e1e208
