### ISSUE TITLE
Implement post content translation via API like Google Translate API

### ISSUE THREAD

**Issue by kunalprakash1309** [the-open-agent/openagent#162]
Currently this website does not support language translation. Because of that it tough for other user who are not familiar with chinese language to understand the content.

I like to work on this by add google translation api.

### Update:

See Twitter: https://twitter.com/bts_bighit/status/1403641483832422405

![image](https://user-images.githubusercontent.com/3787410/121856607-40d43600-cd27-11eb-8549-143abd684094.png)

![image](https://user-images.githubusercontent.com/3787410/121856628-47fb4400-cd27-11eb-9d47-066dc3edfa00.png)

We may provide a translate button for each post, we will also provide a global switch to translate all contents shown.

**Comment by hsluoyz** [comment]
@kunalprakash1309 do you mean the UI of the forum, or the post content of the forum?

**Comment by kunalprakash1309** [comment]
Post content of the forum. @hsluoyz

**Comment by hsluoyz** [comment]
@kunalprakash1309 sounds good, but I hope it will not be a hard-dependency for the code. This part of code should be pluggable.

**Comment by kunalprakash1309** [comment]
@hsluoyz I have one question. Before making commit do I have to remove authorization key from app.conf and Conf.js file?

**Comment by keainye** [comment]
Yes. You can left a key, and let users to fill the value.

**Comment by kunalprakash1309** [comment]
> Yes. You can left a key, and let users to fill the value.

Sorry, I am asking about GoogleClinetIds and other Auth keys

**Comment by hsluoyz** [comment]
Closed for now. Maybe useful in future.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casnode/pull/286

**Comment by hsluoyz** [comment]
@WindSpiritSR we should have a way to disable the translation (hide the "Translate" link).
