### ISSUE TITLE
Dark mode is not working

### ISSUE THREAD

**Issue by kunalprakash1309** [the-open-agent/openagent#163]
Dark mode is not working on clicking the toggle button beside the profile image

https://user-images.githubusercontent.com/42040782/111624460-bc4e4600-8811-11eb-9096-8e74553fbfdd.mp4

**Comment by keainye** [comment]
Got that, working on this.

**Comment by kunalprakash1309** [comment]
I want to work on this issue @hsluoyz

**Comment by hsluoyz** [comment]
Anyone can work on this :)

**Comment by kunalprakash1309** [comment]
This is what I tried to built 

https://user-images.githubusercontent.com/42040782/111852812-6b883b80-893e-11eb-8610-e811e80c2153.mp4
