### ISSUE TITLE
Sync Casnode data with iframe via the comment plugin like Disqus

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#167]
Casbin-forum can provide a "headless" mode (see what "headless" means by googling "Headless Chrome"): it doesn't provide the web UI, only the backend API is used.

A good scenario for this is the comment plugin like Disqus we used: https://casbin.org/docs/en/overview#comment-5283453205

- The comments can map to the replies of the forum.
- The page that comments attach to can map to the post/thread of the forum inside a node.
- We also need to develop a JS plugin to let user website (like Casbin docs: https://casbin.org/) integrate with. The JS plugin will talk to a forum backend API.
- The forum can also setup the web UI, but it's not required.
- For our own usage (aka dogfood), we can map Casbin docs's comments to: https://forum.casbin.com/go/docs

![image](https://user-images.githubusercontent.com/3787410/120918289-4bb71700-c6e6-11eb-9e69-947bdd83fc6b.png)

**Comment by hsluoyz** [comment]
@Kininaru @oranges-eating

**Comment by keainye** [comment]
@hsluoyz I will make a PR to Casdoor JS SDK later today, then I will have a look on this.

**Comment by hsluoyz** [comment]
@oranges-eating
