### ISSUE TITLE
Clicking "Rich List" shows nothing at first, refreshing shows UI.

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#171]
![image](https://user-images.githubusercontent.com/3787410/112234212-fd61b280-8c76-11eb-896d-937ce3f36a10.png)

![image](https://user-images.githubusercontent.com/3787410/112234222-02befd00-8c77-11eb-8517-02111e81e568.png)

![image](https://user-images.githubusercontent.com/3787410/112234241-0b173800-8c77-11eb-9510-7c2ce8bd4e4f.png)

**Comment by hsluoyz** [comment]
@Kininaru

**Comment by keainye** [comment]
Got that, I will fix this bug today or tomorrow.
