### ISSUE TITLE
Support other OSS providers like Tencent

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#176]
Can https://github.com/qor/oss be used here or is there a better solution?

**Comment by keainye** [comment]
I'm afraid not. Casbin forum is using Aliyun Security Token Service (STS) to upload files directly from users' browsers to the OSS server. However, we can only upload files from the server which casbin forum is deployed if we use qor's OSS adapter.

**Comment by hsluoyz** [comment]
@Kininaru I think we need to support other OSS. Can we do the following?

1. If OSS is Aliyun, we still use the STS way.
2. If OSS is others, we use the server-side file uploading.
