### ISSUE TITLE
It is recommended to use bing for in-site search, Baidu in-site search did not search the results.

### ISSUE THREAD

**Issue by Yakumo-Yukari** [the-open-agent/openagent#182]

**Comment by hsluoyz** [comment]
@Yakumo-Yukari did you try Bing? Does Bing work?

**Comment by Yakumo-Yukari** [comment]
> did you try Bing? Does Bing work?

I tried, but bing only included the front page of the forum, so I didn't get search results, maybe SEO needs to be optimized.

**Comment by hsluoyz** [comment]
@Yakumo-Yukari we will solve SEO in: https://github.com/casbin/casbin-forum/issues/122

**Comment by hsluoyz** [comment]
@Yakumo-Yukari SSR is added to support better SEO, see: https://github.com/casbin/casnode/issues/122

**Comment by hsluoyz** [comment]
I confirmed that Baidu in-site search works as expected, closed here.
