### ISSUE TITLE
Provide default avatar image like GitHub when the user doesn't set one and the gravatar.com is unaccessable

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#188]
If the user doesn't set a custom avatar image, the Go backend (already implemented) will try to fetch avatar from gravatar.com. If gravatar.com is unaccessable (e.g. blocked in some areas), then the frontend will provide a default GitHub-identicon-style avatar image.

The default image is dynamically generated in frontend by this lib: https://github.com/stewartlord/identicon.js (can use username as hash for identicon).

Note: the default image is NOT stored in backend or DB.

Fix: https://forum.casbin.com/t/115

**Comment by hsluoyz** [comment]
@Kininaru

**Comment by keainye** [comment]
Got that, working on this.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casnode/pull/236
