### ISSUE TITLE
Fix the too-big image style for mobile view

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#191]
See (in mobile view): https://forum.casbin.com/t/116

![image](https://user-images.githubusercontent.com/3787410/113425062-ca03ee00-9403-11eb-9048-37cb09950a9c.png)

**Comment by hsluoyz** [comment]
@Kininaru

**Comment by keainye** [comment]
Got that. I'll fix this tomorrow.

**Comment by Hanaffi** [comment]
@hsluoyz Can you assign this to me? I'm a GSOC applicant

**Comment by hsluoyz** [comment]
@Hanaffi anyone can work on it, go ahead!

**Comment by Hanaffi** [comment]
@hsluoyz Can you give me some hints on what file should I work on?
Its my first time to contribute to your project
