### ISSUE TITLE
Can users add tags to posts when they publish them?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [the-open-agent/openagent#197]
Adding tags to articles makes it easier for users to find the articles they are interested in

**Comment by hsluoyz** [comment]
@Yakumo-Yukari can you give an example site about the tag feature? Like other forums.

**Comment by hsluoyz** [comment]
@Kininaru

**Comment by Yakumo-Yukari** [comment]
> can you give an example site about the tag feature? Like other forums.



> @Yakumo-Yukari can you give an example site about the tag feature? Like other forums.

![1](https://user-images.githubusercontent.com/12076232/113804463-2747c880-9791-11eb-8aca-6dc78c130a50.png)
![3](https://user-images.githubusercontent.com/12076232/113804467-29aa2280-9791-11eb-910e-6ecf41b12205.png)

**Comment by hsluoyz** [comment]
@Yakumo-Yukari done:

![image](https://user-images.githubusercontent.com/3787410/120918195-b7e54b00-c6e5-11eb-8e00-8bc4298f58b5.png)
