### ISSUE TITLE
Why not use a UI framework on the front end?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [the-open-agent/openagent#199]
Hey, why not use Ant-design, wouldn't using a UI framework make front-end development easier?

**Comment by hsluoyz** [comment]
1. Antd is usually used for to-B apps, like admin portal. The antd UI is all similar. Forum is mainly a to-C app, it needs UI customization.
2. Antd doesn't support mobile.
3. We follow the v2ex UI style, which is not antd.
