### ISSUE TITLE
Setup Crowdin for easier i18n translation

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#200]
Currently we use JSON for translation: https://github.com/casbin/casnode/tree/master/web/src/locales

Finally we will move to a translation platform like how we did for Casbin-website: https://crowdin.com/project/casbin

The Crowdin project is already ready to use: https://crowdin.com/project/casnode . We need to setup this repo to use it.

**Comment by ErikQQY** [comment]
Working on this issue.
