### ISSUE TITLE
To make the node information less monotonous, let's add a custom background image function to the node display, shall we?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [the-open-agent/openagent#220]
![1](https://user-images.githubusercontent.com/12076232/115325354-10a46700-a1be-11eb-8933-61c93dfc0490.png)

**Comment by hsluoyz** [comment]
@Kininaru

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casnode/pull/221
