### ISSUE TITLE
Cannot focus textbox from the bottom

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#239]
Post: https://forum.casbin.com/new/casbin

![image](https://user-images.githubusercontent.com/3787410/119510837-6dd69e00-bda4-11eb-900a-cf084ae777f9.png)

Similar to reply: https://forum.casbin.com/t/146

![image](https://user-images.githubusercontent.com/3787410/119510899-7d55e700-bda4-11eb-9a1c-b7d5a33ad6ec.png)

**Comment by PranjayPathak** [comment]
Hi @hsluoyz, can I work on this issue?
