### ISSUE TITLE
errorUsernameExistedOrEmailExisted

### ISSUE THREAD

**Issue by xcaptain** [the-open-agent/openagent#25]
https://github.com/casbin/casbin-forum/blob/996ca90d6c1bc47e7da4b18499c5615377193b76/controllers/account.go#L80-L85

I have already registered my account using github, but when I click the signin using github account button again, I got this `errorUsernameExistedOrEmailExisted` error

**Comment by hsluoyz** [comment]
@kocoler can you take a look at this issue?

**Comment by kocoler** [comment]
I found that I don’t know why you didn’t get the account information when you registered on github. Just having the email, which caused the problem. I will improve the authentication process to prevent such things from happening.

**Comment by kocoler** [comment]
I have fixed it. When the new version goes online, it can be used normally, and it will automatically fix the problem of missing information before.

**Comment by hsluoyz** [comment]
@kocoler where's the PR?
