### ISSUE TITLE
The session is lost after logging in

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#266]
We know this PR: https://github.com/casbin/casnode/pull/263 caused the issue. But we didn't know how.

**Comment by Kininaru** [comment]
Now we known that function `object/member.go GetMemberOnlineNum` is the reason of the issue, but I don't know why. 

```go
func GetMemberOnlineNum() int {
	total := 0
	members := GetMembersFromCasdoor()
	for _, member := range members {
		if member.OnlineStatus {
			total++
		}
	}

	return total
}
```

If all `member` in `members` have a online status `false`, then the sign in will fail. 
If any of them are `true` (even if you set them to true before the if statement`, sign in won't fail.
