### ISSUE TITLE
The administrator cannot enter the administrator background 

### ISSUE THREAD

**Issue by oranges-eating** [the-open-agent/openagent#275]
Logging in with an administrator account will not display the background management button, nor can you open /admin, but the background data can be updated normally.

**Comment by oranges-eating** [comment]
I will solve it

**Comment by hsluoyz** [comment]
@oranges-eating can you give example?

**Comment by oranges-eating** [comment]
> @oranges-eating can you give example?

http://www.killerwing.xyz:7000/
username:user_2
password:123456
the user is administrator, not display the background management button.
![1](https://user-images.githubusercontent.com/53165082/121811489-2488b880-cc97-11eb-8237-5257ed68cbc9.JPG)

**Comment by hsluoyz** [comment]
This is a simple bug I think. Need a fix.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casnode/pull/277
