### ISSUE TITLE
bug: user balance not updated after login

### ISSUE THREAD

**Issue by oranges-eating** [the-open-agent/openagent#276]
the user balance in the rightbar next to the home page will not be updated after logging in. The balance in the personal information is updated normally.the balance is unequal.And Daily checkin bonus can be performed multiple times
![2](https://user-images.githubusercontent.com/53165082/121811608-7af5f700-cc97-11eb-935b-f41f0b20934a.JPG)
![2](https://user-images.githubusercontent.com/53165082/121813944-07f17e00-cca1-11eb-9b28-dce24dcb6660.JPG)

**Comment by oranges-eating** [comment]
I will solve it

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casnode/pull/283
