### ISSUE TITLE
When logged in, changing language doesn't work

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#281]
When logged in, after choosing English, it doesn't work

![image](https://user-images.githubusercontent.com/3787410/122080084-8fb9c280-ce30-11eb-8b86-043bbd709a04.png)

Still Chinese

![image](https://user-images.githubusercontent.com/3787410/122080134-9b0cee00-ce30-11eb-8bcf-7afb75e463c9.png)

**Comment by hsluoyz** [comment]
@Kininaru

**Comment by keainye** [comment]
@hsluoyz This may be the problem of `UpdateMemberToCasdoor`. I will fix that.

**Comment by hsluoyz** [comment]
@Kininaru @oranges-eating is this already fixed?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casnode/pull/283

**Comment by keainye** [comment]
@hsluoyz Yes, already fixed.
