### ISSUE TITLE
The search result for "111" doesn't actually have "111"

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#282]
https://forum.casbin.com/search?keyword=111

![image](https://user-images.githubusercontent.com/3787410/122084841-c265ba00-ce34-11eb-9844-1f35f7eb97c0.png)

**Comment by hsluoyz** [comment]
@Kininaru

**Comment by keainye** [comment]
@hsluoyz Image url contains `111`. I will fix that.

**Comment by hsluoyz** [comment]
@Kininaru and the search speed is so slow..

**Comment by keainye** [comment]
@hsluoyz Content Download spent too much time...Trying to find out the reason.

**Comment by keainye** [comment]
As for the search speed, I think it is because search backend called `getMemberFromCasdoor` to get member avatars. We can add a cache to store members in Casnode to make member operations faster.
