### ISSUE TITLE
dial tcp [::1]:8000: connectex

### ISSUE THREAD

**Issue by ha666** [the-open-agent/openagent#302]
panic: Get "http://localhost:8000/api/get-users?owner=casbin-forum": dial tcp [::1]:8000: connectex: No connection could be made because the target machine actively refused it.

**Comment by oranges-eating** [comment]
Now casnode uses casdoor for member operations, so before starting casnode, you need to start casdoor first, which is the address of casdoor https://github.com/casbin/casdoor.

**Comment by ha666** [comment]
Thank you, it's solved!
