### ISSUE TITLE
[ Web ] Sign Up Link is hidden behind github icon

### ISSUE THREAD

**Issue by NikhilSharma03** [the-open-agent/openagent#306]
* Description *
The signup link is hidden behind the GitHub icon on smaller screens.

## Image
![Screenshot from 2021-06-22 13-19-50](https://user-images.githubusercontent.com/58226527/122885615-de012100-d35c-11eb-9842-36b42ee8d990.png)

## Note For Reviewer
If possible, I would love to work on this issue. Thank you.

**Comment by hsluoyz** [comment]
@NikhilSharma03 what I saw is this:

![image](https://user-images.githubusercontent.com/3787410/122887466-828e5d80-d373-11eb-98a8-8d605072ec8a.png)

Why do you see that?

**Comment by NikhilSharma03** [comment]
@hsluoyz It's on smaller screens. Can i work on this issue?

**Comment by hsluoyz** [comment]
@NikhilSharma03 ok

**Comment by NikhilSharma03** [comment]
@hsluoyz Thank you

**Comment by hsluoyz** [comment]
This icon is usually turned off for a production use. So this is not an issue.
