### ISSUE TITLE
What is the endpoint port for? 8000: connect: connection refused

### ISSUE THREAD

**Issue by chenyangguang** [the-open-agent/openagent#311]
➜  casnode git:(master) ✗ bee run       
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v2.0.2
2021/06/23 22:10:46 WARN     ▶ 0001 Running application outside of GOPATH
2021/06/23 22:10:46 INFO     ▶ 0002 Using 'casnode' as 'appname'
2021/06/23 22:10:47 INFO     ▶ 0003 Initializing watcher...
2021/06/23 22:10:48 SUCCESS  ▶ 0004 Built Successfully!
2021/06/23 22:10:48 INFO     ▶ 0005 Restarting 'casnode'...
2021/06/23 22:10:48 SUCCESS  ▶ 0006 './casnode' is running...
2021-06-23 22:10:49.640757 I | 载入sego词典 ./dictionary/dictionary.txt
2021-06-23 22:10:51.017003 I | sego词典载入完毕
[xorm] [warn]  2021/06/23 22:10:51.024227 Table session Column session_data db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027694 Table topic Column author db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027707 Table topic Column node_id db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027710 Table topic Column node_name db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027713 Table topic Column title db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027715 Table topic Column created_time db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027718 Table topic Column tags db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027721 Table topic Column last_reply_user db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027723 Table topic Column last_reply_time db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027726 Table topic Column reply_count db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027728 Table topic Column up_count db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027731 Table topic Column hit_count db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027733 Table topic Column hot db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027735 Table topic Column favorite_count db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027738 Table topic Column home_page_top_time db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027742 Table topic Column tab_top_time db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027744 Table topic Column node_top_time db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027747 Table topic Column deleted db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027750 Table topic Column editor_type db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.027752 Table topic Column content db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.030766 Table reply Column author db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.030775 Table reply Column topic_id db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.030778 Table reply Column created_time db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.030780 Table reply Column deleted db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.030783 Table reply Column thanks_num db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.030785 Table reply Column editor_type db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.030788 Table reply Column content db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.033761 Table poster Column advertiser db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.033769 Table poster Column link db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.033772 Table poster Column picture_link db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.033774 Table poster Column state db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.036738 Table translator Column name db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.036767 Table translator Column translator db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.036770 Table translator Column key db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.036772 Table translator Column enable db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.036775 Table translator Column visible db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039766 Table node Column name db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039776 Table node Column created_time db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039779 Table node Column desc db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039781 Table node Column image db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039784 Table node Column background_image db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039786 Table node Column header_image db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039788 Table node Column background_color db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039791 Table node Column background_repeat db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039793 Table node Column tab_id db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039795 Table node Column parent_node db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039797 Table node Column plane_id db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039800 Table node Column sorter db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039802 Table node Column hot db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039804 Table node Column moderators db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039807 Table node Column mailing_list db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.039809 Table node Column google_group_cookie db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.042845 Table favorites Column favorites_type db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.042854 Table favorites Column object_id db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.042857 Table favorites Column created_time db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.042860 Table favorites Column member_id db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.045702 Table tab Column name db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.045710 Table tab Column sorter db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.045718 Table tab Column created_time db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.045722 Table tab Column default_node db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.045725 Table tab Column home_page db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.048395 Table notification Column notification_type db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.048403 Table notification Column object_id db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.048406 Table notification Column created_time db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.048408 Table notification Column sender_id db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.048410 Table notification Column receiver_id db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.048412 Table notification Column status db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.050935 Table basic_info Column value db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.053562 Table plane Column name db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.053570 Table plane Column sorter db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.053573 Table plane Column created_time db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.053575 Table plane Column image db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.053578 Table plane Column background_color db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.053580 Table plane Column color db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.053582 Table plane Column visible db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.056475 Table consumption_record Column amount db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.056484 Table consumption_record Column balance db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.056487 Table consumption_record Column consumer_id db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.056490 Table consumption_record Column object_id db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.056492 Table consumption_record Column receiver_id db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.056494 Table consumption_record Column created_time db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.056496 Table consumption_record Column consumption_type db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.059659 Table browse_record Column member_id db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.059669 Table browse_record Column record_type db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.059671 Table browse_record Column object_id db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.059674 Table browse_record Column created_time db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.059676 Table browse_record Column expired db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.062967 Table upload_file_record Column file_name db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.062990 Table upload_file_record Column file_path db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.062993 Table upload_file_record Column file_url db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.063015 Table upload_file_record Column file_type db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.063018 Table upload_file_record Column file_ext db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.063020 Table upload_file_record Column member_id db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.063022 Table upload_file_record Column created_time db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.063040 Table upload_file_record Column size db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.063042 Table upload_file_record Column views db default is NULL, struct default is 
[xorm] [warn]  2021/06/23 22:10:51.063044 Table upload_file_record Column desc db default is 'NULL', struct default is 
[xorm] [warn]  2021/06/23 22:10:51.063046 Table upload_file_record Column deleted db default is NULL, struct default is 
panic: Get "http://localhost:8000/api/get-users?owner=casbin-forum": dial tcp [::1]:8000: connect: connection refused

goroutine 1 [running]:
github.com/casbin/casnode/object.GetMembersFromCasdoor(0x0, 0x0, 0x0)
	/Users/c/workdir/casnode/object/sync.go:129 +0x7b
github.com/casbin/casnode/object.GetMemberOnlineNum(0xc000040024)
	/Users/c/workdir/casnode/object/member.go:485 +0x25
github.com/casbin/casnode/object.UpdateOnlineMemberNum()
	/Users/c/workdir/casnode/object/basic.go:233 +0x25
github.com/casbin/casnode/object.InitForumBasicInfo()
	/Users/c/workdir/casnode/object/basic.go:41 +0x30
main.main()
	/Users/c/workdir/casnode/main.go:36 +0x55

**Comment by kocoler** [comment]
`casdoorEndpoint` point to the backend of your `casdoor`.
You should run another application [casdoor](https://github.com/casbin/casdoor) at the same time.

**Comment by hsluoyz** [comment]
@chenyangguang  see: https://casnode.org/docs/main-features#use-casdoor-to-manage-members
