### ISSUE TITLE
Put all frontend configurations into one config file

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#325]
Like logo, forum name, forum description, etc. All these things should be easily configurable in one place, like inside a single config file in the frontend project (/web).

![image](https://user-images.githubusercontent.com/3787410/126073411-ec8a65ef-d838-4991-bd1a-3b0449c8fd3c.png)

![image](https://user-images.githubusercontent.com/3787410/126073417-1eff11ec-b6a8-4733-8abf-88a7ff0a7114.png)

**Comment by hsluoyz** [comment]
@oranges-eating

**Comment by oranges-eating** [comment]
yes,I will work for it

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casnode/pull/327
