### ISSUE TITLE
Replace Casnode's Member struct with Casdoor's User struct everywhere

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#349]
We don't use `UpdateMemberToCasdoor()` any more.

**Comment by hsluoyz** [comment]
@Kininaru @WindSpiritSR @sh1luo @oranges-eating

**Comment by oranges-eating** [comment]
ok,work for it

**Comment by hsluoyz** [comment]
Done: https://github.com/casbin/casnode/commit/4b23e564bed9d2a1ded4fb7c8ff04353b94c2b24
