### ISSUE TITLE
Pagination is broken for node topic list

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#368]
Node topic list: https://forum.casbin.com/go/casbin , there's no pagination:

![image](https://user-images.githubusercontent.com/3787410/144600558-b9e84b99-d745-4090-87c8-abafe9c6d295.png)

It should show like this: https://v2ex.com/go/apple

![image](https://user-images.githubusercontent.com/3787410/144588173-1086f9c9-1ba3-45d7-a940-7cb9850a0719.png)

Maybe we already have the code but it's hidden for some reason. (or maybe not)

**Comment by shubhangi013** [comment]
> Like: https://forum.casbin.com/recent
> 
> The topics are not complete. But there's no pagination.
> 
> ![image](https://user-images.githubusercontent.com/3787410/131205650-8332f611-76e4-4a71-8298-247e4e999f35.png)

Hey! I'm new to contributing to casnode, I'd like to work on this issue. Could you tell me how'd you want the pagination to be?

**Comment by hsluoyz** [comment]
@shubhangi013 see my update in the issue top.

**Comment by shubhangi013** [comment]
> @shubhangi013 see my update in the issue top.

Oh alright! Thankyou.

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casnode/commit/7ffc0c78cf9e1f83bee3d53ccc915c3e54d25f73
