### ISSUE TITLE
是否可以为帖子or文章增加点赞功能及点赞用户列表

### ISSUE THREAD

**Issue by Yakumo-Yukari** [the-open-agent/openagent#89]
![2020-11-10 122720](https://user-images.githubusercontent.com/12076232/98627867-2e88b880-2350-11eb-9215-0d8a1d197e4c.png)

类似图片中这样的功能

**Comment by hsluoyz** [comment]
@kocoler

**Comment by kocoler** [comment]
@hsluoyz 是否要加入？

**Comment by hsluoyz** [comment]
@kocoler 这个功能很好，可以加入

@Yakumo-Yukari 请问图片出处是哪里？给个URL方便参考实现

**Comment by Yakumo-Yukari** [comment]
> @kocoler 这个功能很好，可以加入
> 
> @Yakumo-Yukari 请问图片出处是哪里？给个URL方便参考实现

https://www.xiaoduyu.com/posts/5e968c971415a620b466b440

https://mlog.club/topic/609

> @kocoler 这个功能很好，可以加入
> 
> @Yakumo-Yukari 请问图片出处是哪里？给个URL方便参考实现

> @kocoler 这个功能很好，可以加入
> 
> @Yakumo-Yukari 请问图片出处是哪里？给个URL方便参考实现

这两个网站
