### ISSUE TITLE
请问帖子文字内容和图片数据是统一写入Content字段吗？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [the-open-agent/openagent#90]
就是内容是存储到Content字段的 没有帖子的img字段吗  如果要单独的调用显示帖子内容的图片要怎么做呢？

**Comment by hsluoyz** [comment]
@kocoler

**Comment by kocoler** [comment]
是以url形式的放到数据库的
图片存放在ali-oss

**Comment by Yakumo-Yukari** [comment]
> 是以url形式的放到数据库的
> 图片存放在ali-oss

请问是和帖子内容一起存在Content字段吗

**Comment by kocoler** [comment]
> 请问是和帖子内容一起存在Content字段吗

是的

> 如果要单独的调用显示帖子内容的图片要怎么做呢？

如果是通过论坛自带上传功能上传的话，可以在文件库中找到，作为外链分享
否则的话，暂时没办法通过论坛自带功能做到，也没有提供这个api

然后请问这个 `单独的调用显示帖子内容的图片` 是要干嘛呢......

**Comment by Yakumo-Yukari** [comment]
> > 请问是和帖子内容一起存在Content字段吗
> 
> 是的
> 
> > 如果要单独的调用显示帖子内容的图片要怎么做呢？
> 
> 如果是通过论坛自带上传功能上传的话，可以在文件库中找到，作为外链分享
> 否则的话，暂时没办法通过论坛自带功能做到，也没有提供这个api
> 
> 然后请问这个 `单独的调用显示帖子内容的图片` 是要干嘛呢......
![2020-11-11 162031](https://user-images.githubusercontent.com/12076232/98787088-ffe70c80-2439-11eb-9e58-65418a881b9b.png)

是想做成贴吧这种列表里显示图片效果  如果帖子有图片就显示没有就不显示 所以就想问下为什么不把内容和图片分2个字段呢

**Comment by hsluoyz** [comment]
这个其实也不难，直接解析content，拿到所有图片URL即可

**Comment by Yakumo-Yukari** [comment]
> 这个其实也不难，直接解析content，拿到所有图片URL即可

就是在展示的时候先直接取到content 然后用js 正则取图片然后在返回结果吗   感觉有点麻烦
