### ISSUE TITLE
大哥写react太不严肃了

### ISSUE THREAD

**Issue by open-trade** [the-open-agent/openagent#91]

**Comment by hsluoyz** [comment]
Hi, can you be more specific?

**Comment by open-trade** [comment]
就是感叹一下，反正我也修的差不多了

**Comment by hsluoyz** [comment]
@open-trade we are an open-source project. Please contribute your code via PR so we can together make this project better.

**Comment by open-trade** [comment]
只是自定义修改的东西太多，不好发PR

**Comment by hsluoyz** [comment]
@open-trade can you join our QQ group: 546057381 so we can have a better discussion about it?
