### ISSUE TITLE
Set the highlighted tab to "All" by default

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#93]
Currently, when you browse https://forum.casbin.com/ , you will see all posts, which corresponds to the "All" tab, but that tab is not highlighted.

![image](https://user-images.githubusercontent.com/3787410/102340933-143a9e00-3fd2-11eb-9022-9282ac0f4875.png)

**Comment by kocoler** [comment]
I think this may not a bug. In the past, the v2ex also displayed all by default but no tag was selected. So the previous design was like that.
#94 
And this pr may works. It highlighted the tab whose id is "all" and display all topics by default.

**Comment by noneback** [comment]
#96
I also highlighted the tab whose id is the same as rootTabId(like "all" in my pr),and it also put the last used tab record in localStorage so that user can see it as soon as opening forum

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin-forum/pull/94 and https://github.com/casbin/casbin-forum/pull/96
