### ISSUE TITLE
AdminNode add a new node display error when db has no node data

### ISSUE THREAD

**Issue by Arealm** [the-open-agent/openagent#98]
![image](https://user-images.githubusercontent.com/26957122/102866421-33be4480-4472-11eb-889f-8689914e0888.png)

**Comment by hsluoyz** [comment]
@Arealm did you setup the Go backend?

**Comment by noneback** [comment]
I think that error happens when the DB has no node data.The `this.state.form.parentNode` and  `this.state.nodes` in function `renderSelect` is null,and leads to that error.

**Comment by noneback** [comment]
I tried to solve it in pr #103

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin-forum/commit/bb9e9e5b48c5105aa67c1acad9a4f3aaed6baf56
