### ISSUE TITLE
Add a rich-text (HTML) editor option besides the current markdown editor

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#99]
Like: https://github.com/margox/braft-editor

**Comment by noneback** [comment]
How about [Vditor](https://github.com/Vanessa219/vditor)?
It provides a rich-text md editor like typora.

**Comment by hsluoyz** [comment]
@noneback Vditor is cool.

But we should support all existing feautures like uploading image, files.

**Comment by oceanlvr** [comment]
`braft-editor` is a good rich text editor, it can easily export `html` content, which is compatible with our existing markdown editor and can be migrated naturally
I will try to add it to our forum
